import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Header/Page";
import Footer from "./Fooder/page";

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" datatheme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#286054]`}
      >
        <Header></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
